"""Windows version metadata for the sidecar exe and NSIS installer.

Two consumers, one source (``package.json``):

- ``windows.spec`` imports :func:`write_version_file` to stamp a
  ``VSVersionInfo`` resource into ``RunwaySidecar.exe`` (Explorer →
  Properties → Details, and the SmartScreen/Apps & Features metadata).
- CI and ``make sidecar-installer`` run ``python sidecar_app/spec/win_version.py``
  to get the values ``makensis`` needs::

      $ python sidecar_app/spec/win_version.py
      VERSION=2.12.0+edge.abc1234
      PRODUCT_VERSION_QUAD=2.12.0.0

Windows version resources are four 16-bit integers, so any pre-release or
``+edge.<sha>`` suffix is dropped for the numeric fields (the full string is
kept in the ``ProductVersion`` text field).
"""

from __future__ import annotations

import json
import pathlib
import re
import sys

_ROOT = pathlib.Path(__file__).resolve().parents[2]


def read_version(root: pathlib.Path = _ROOT) -> str:
    data = json.loads((root / "package.json").read_text(encoding="utf-8"))
    return str(data.get("version") or "0.0.0")


def numeric_parts(version: str) -> tuple[int, int, int, int]:
    """``"v2.12.0-rc1+edge.abc"`` → ``(2, 12, 0, 0)``; always four clamped ints."""
    nums = [int(n) for n in re.findall(r"\d+", re.split(r"[-+]", version.lstrip("vV"), maxsplit=1)[0])]
    nums = (nums + [0, 0, 0, 0])[:4]
    return tuple(min(n, 65535) for n in nums)  # type: ignore[return-value]


def quad(version: str) -> str:
    return ".".join(str(n) for n in numeric_parts(version))


_TEMPLATE = """# UTF-8 — generated by sidecar_app/spec/win_version.py; do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={nums},
    prodvers={nums},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', 'Runway'),
        StringStruct('FileDescription', 'Runway Sidecar'),
        StringStruct('FileVersion', '{quad}'),
        StringStruct('InternalName', 'RunwaySidecar'),
        StringStruct('LegalCopyright', 'Runway contributors. Licensed under AGPL-3.0.'),
        StringStruct('OriginalFilename', 'RunwaySidecar.exe'),
        StringStruct('ProductName', 'Runway Sidecar'),
        StringStruct('ProductVersion', '{version}')
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def render_version_info(version: str) -> str:
    safe = version.replace("'", "")
    return _TEMPLATE.format(nums=numeric_parts(version), quad=quad(version), version=safe)


def write_version_file(dest: str | pathlib.Path, root: pathlib.Path = _ROOT) -> str:
    dest = pathlib.Path(dest)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(render_version_info(read_version(root)), encoding="utf-8")
    return str(dest)


def main() -> int:
    version = read_version()
    print(f"VERSION={version}")
    print(f"PRODUCT_VERSION_QUAD={quad(version)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
